# Generated by Django 3.0.5 on 2020-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('q_open', models.CharField(max_length=120)),
                ('q_high', models.CharField(max_length=120)),
                ('q_low', models.CharField(max_length=120)),
                ('q_close', models.CharField(max_length=120)),
                ('q_adj_close', models.CharField(max_length=120)),
                ('q_volume', models.CharField(max_length=120)),
            ],
        ),
    ]
