# Generated by Django 3.0.5 on 2020-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='q_adj_close',
            field=models.FloatField(max_length=120),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='q_close',
            field=models.FloatField(max_length=120),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='q_high',
            field=models.FloatField(max_length=120),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='q_low',
            field=models.FloatField(max_length=120),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='q_open',
            field=models.FloatField(max_length=120),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='q_volume',
            field=models.FloatField(max_length=120),
        ),
    ]
