# Generated by Django 3.0.5 on 2020-04-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20200426_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
