# Generated by Django 3.0.5 on 2020-04-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_delete_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('q_open', models.FloatField(max_length=120)),
                ('q_high', models.FloatField(max_length=120)),
                ('q_low', models.FloatField(max_length=120)),
                ('q_close', models.FloatField(max_length=120)),
                ('q_adj_close', models.FloatField(max_length=120)),
                ('q_volume', models.FloatField(max_length=120)),
                ('q_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='trade.Quotes_Name')),
            ],
        ),
    ]
