# Generated by Django 3.0.5 on 2020-04-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_quotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
