# Generated by Django 3.0.5 on 2020-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20200426_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes_name',
            name='name',
            field=models.TextField(),
        ),
    ]
