# Generated by Django 3.0.5 on 2020-04-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
